[project]
name = "pims"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.3",
    "pymongo>=4.17.0",
    "python-ldap>=3.4.7",
]

[dependency-groups]
dev = [
    "ptpython>=3.0.32",
    "pytest>=9.1.1",
    "pytest-sphinx>=0.7.1",
    "sphinx>=9.0.4",
    "sphinx-book-theme>=1.4.0",
]

[tools.pytest.ini_options]
pythonpath = ["src", "tests"]
addopts = [
    "--doctest-modules",
    "--ignore data",
    "--ignore database"
]
