# processManagement:
#     fork: true # background the process by default
net:
    bindIp: localhost # other interfaces can be listed here space seperated
    port: 27017
storage:
    dbPath: dbdata
systemLog:
    destination: file
    path: dbdata/mongod.log
    logAppend: true
# security:
#     authorization: enabled # Only connections on localhost should be able to perform any actions by default
